FROM registry.supos.ai/library/adoptopenjdk:jdk8u312-0.29.0-openj9-tls

RUN mkdir -p /home/local/bin && \
    mkdir -p /home/local/conf && \
    mkdir -p /home/local/libs && \
    mkdir -p /home/local/modules && \
    mkdir -p /home/local/tools