FROM registry.supos.ai/library/openj9:aarch64-open-11.0.18_10-jdk

RUN mkdir -p /home/local/bin && \
    mkdir -p /home/local/conf && \
    mkdir -p /home/local/libs && \
    mkdir -p /home/local/modules && \
    mkdir -p /home/local/tools