FROM registry.supos.ai/library/openjdk:8-jdk-alpine

RUN mkdir -p /home/local/bin && \
    mkdir -p /home/local/conf && \
    mkdir -p /home/local/libs && \
    mkdir -p /home/local/modules && \
    mkdir -p /home/local/tools