FROM registry.supos.ai/library/adoptopenjdk:8u275-jdk-openj9

RUN mkdir -p /home/local/bin && \
    mkdir -p /home/local/conf && \
    mkdir -p /home/local/libs && \
    mkdir -p /home/local/modules && \
    mkdir -p /home/local/tools